spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todoboard
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
